### ISSUE TITLE
Error in the console when navigating in the lumx documentation

### ISSUE THREAD

**Issue by arnaudvalle** [lumapps/lumX#525]
I don't think it really breaks anything (yet) but it's not great... 

1. Go to http://ui.lumapps.com/
2. Click on CSS in the main nav
3. Click on Component in the main nav
4. Check the JS console logs

```
Possibly unhandled rejection: {"$id":1,"type":2,"message":"The transition has been superseded by a different transition","detail":{"_identifier":"app.components.button","_definition":{"self":{"url":"/button","views":{"main@":{"templateUrl":"/includes/modules/button/button.html"}},"name":"app.components.button"},"__stateObjectCache":{"nameGlob":null},"name":"app.components.button","parent":{"self":{"url":"/components","views":{"sidebar@":{"templateUrl":"/includes/layout/sub-nav/sub-nav-components.html"}},"redirectTo":"app.components.button","name":"app.components"},"__stateObjectCache":{"nameGlob":null},"name":"app.components","parent":{"self":{"abstract":true,"views":{"header":{"templateUrl":"/includes/layout/header/header.html"}},"name":"app"},"__stateObjectCache":{"nameGlob":null},"name":"app","parent":{"self":{"name":"","url":"^","views":null,"params":{"#":{"value":null,"type":"hash","dynamic":true}},"abstract":true},"__stateObjectCache":{"nameGlob":null},"name":"","parent":null,"url":{"config":{"params":"...","strict":true,"caseInsensitive":false},"_cache":{"path":["..."]},"_children":[{"config":{"params":{},"strict":true,"caseInsensitive":false},"_cache":{"path":["...","..."],"parent":"...","pattern":{},"segments":["/"],"weights":[1]},"_children":[],"_params":[],"_segments":["/"],"_compiled":["/"],"pattern":"/"},{"config":{"params":{},"strict":true,"caseInsensitive":false},"_cache":{"path":["...","..."],"parent":"...","pattern":{},"segments":["/","getting-started"],"weights":[1,2]},"_children":[{"config":{"params":{},"strict":true,"caseInsensitive":false},"_cache":{"path":["...","...","..."],"parent":"...","pattern":{},"segments":["/","getting-started","/","installation"],"weights":[1,2,1,2]},"_children":[],"_params":[],"_segments":["/installation"],"_compiled":["/installation"],"pattern":"/installation"},{"config":{"params":{},"strict":true,"caseInsensitive":false},"_cache":{"path":["...","...","..."],"parent":"...","pattern":{},"segments":["/","getting-started","/","customization"],"weights":[1,2,1,2]},"_children":[],"_params":[],"_segments":["/
```

I'm guessing it's some compatibility issue between the angularjs version and ui-router, something like that... (most likely related to https://github.com/angular-ui/ui-router/issues/3404)

**Comment by christopherthielen** [comment]
I'm very glad you linked to that ui-router issue because I was able to reproduce the problem with this app.  I'll get a fix in ui-router soon.

**Comment by christopherthielen** [comment]
Fixed in up-router 1.0.4

**Comment by arnaudvalle** [comment]
@christopherthielen thanks a lot for fixing this, works like a charm ;)

**Comment by haoyongliang** [comment]
i'm used angular1.6,ui-router is 1.0.4, this question still Existence
